### ISSUE TITLE
Question UUID

### ISSUE THREAD

**Issue by smoreau** [publicissapient-france/xke-extreme-startup#13]
Is it really necessary to send the question generated UUID as part of the question to the clients?

**Comment by seblm** [comment]
Yes it is : it's the only for a player to know if he answers correctly to a given question by reviewing his personal page (http://<server>:3000/players/<player-id>).

Maybe there is a better solution to give feedback to players ?

**Comment by smoreau** [comment]
Oh yeah, I didn't think of the review page.
No, let's keep as it is.
