### ISSUE TITLE
What is the HTTP return code of url/?random 

### ISSUE THREAD

**Issue by jeantil** [publicissapient-france/xke-extreme-startup#5]
the question contains an URL to be requested by the client which returns an HTTP code which is the answer

**Comment by jeantil** [comment]
J'ai regardé un peu comment fonctionne le serveur. Pour répondre à la question de seb, c'est pas hyper clean. 

Le serveur instancie un thread pour chaque joueur enregistré et conserve une référence sur tous les threads dans une hashmap [key=player.uuid,value=thread] chaque thread contient un quizz master pour le joueur mais référence des objets partagés : le score board et la question factory.

je vais faire une premiere implementation, carrément cradingue basée sur une map globale qui stocke le code réponse en fonction du uuid de la question
j'avoue que tester ça va être pénible (je ne connais pas assez cucumber)

**Comment by jeantil** [comment]
il est assez simple de faire un DOS sur le serveur: il suffit d'un petit programme qui enregistre un max de joueurs

**Comment by seblm** [comment]
Le serveur n'est pas sensé être super secure en effet car on reste dans l'esprit bon enfant d'un évènement local. Normalement.

Une des règles du concours est : ne pas attaquer le serveur

**Comment by jeantil** [comment]
Fermé par erreur, 

J'ai discuté avec olivier, il a des idées sur comment améliorer le truc, je lui réaffecte la tâche :)
